/**
 * V131 LayeredMemoryStore — unified facade for all 5 memory layers
 * Single entry point for L0–L4 operations.
 */

import { META_RULES } from './MetaRules';
import { episodicMemory } from './EpisodicMemory';
import { patternExtractor } from './PatternExtractor';
import { insightIndexer } from './InsightIndexer';
import { globalFactsStore } from './GlobalFactsStore';
import { skillRegistry } from '../skills/skillRegistry';
import type { CrystallizedSkill } from './PatternExtractor';
import type { InsightEntry } from './InsightIndexer';
import type { SkillDefinition } from '../skills/types';
import type { EpisodicEntry } from './EpisodicMemory';

class LayeredMemoryStoreImpl {
  // ─── L4: Episodic ─────────────────────────────────────────────────────────────

  /** Write an episodic entry, returns the entry id */
  async writeEpisodic(entry: Omit<EpisodicEntry, 'id'>): Promise<string> {
    return episodicMemory.write(entry);
  }

  /** Query recent episodic entries by taskType */
  async queryEpisodic(taskType: string, limit?: number): Promise<EpisodicEntry[]> {
    return episodicMemory.query(taskType, limit);
  }

  // ─── L4→L3: Crystallization ────────────────────────────────────────────────

  /**
   * After an episodic write, check if patterns suggest a new skill.
   * Returns a draft CrystallizedSkill if threshold met (≥3 similar entries).
   * Does NOT auto-enable the skill — caller should prompt user.
   */
  async checkAndCrystallize(): Promise<CrystallizedSkill | null> {
    // Find all pattern signatures with ≥ 3 occurrences
    const allEntries = await episodicMemory.query('', 500);
    if (allEntries.length < 3) return null;

    const bySig = new Map<string, EpisodicEntry[]>();
    for (const e of allEntries) {
      const list = bySig.get(e.patternSignature) ?? [];
      list.push(e);
      bySig.set(e.patternSignature, list);
    }

    for (const [, entries] of bySig) {
      if (entries.length >= 3) {
        const skill = patternExtractor.extract(entries);
        if (skill) return skill;
      }
    }
    return null;
  }

  // ─── L1: Insight Index ──────────────────────────────────────────────────────

  /** Index a skill for fast L1 routing */
  buildInsightIndex(skill: SkillDefinition): void {
    const entry = insightIndexer.buildIndex({ id: skill.id, name: skill.name, trigger: skill.trigger ?? skill.name });
    insightIndexer.upsert(entry);
  }

  /** Search for skills by task type */
  searchInsights(taskType: string): string[] {
    return insightIndexer.search(taskType);
  }

  /** Get all insight entries */
  getAllInsights(): InsightEntry[] {
    return insightIndexer.getAll();
  }

  // ─── L0: MetaRules ──────────────────────────────────────────────────────────

  getMetaRules(): readonly string[] {
    return META_RULES;
  }

  // ─── L2: Global Facts ───────────────────────────────────────────────────────

  async getGlobalFact(key: string): Promise<unknown> {
    return globalFactsStore.get(key);
  }

  async setGlobalFact(key: string, value: unknown): Promise<void> {
    return globalFactsStore.set(key, value);
  }

  async getAllGlobalFacts(): Promise<ReturnType<typeof globalFactsStore.getAll>> {
    return globalFactsStore.getAll();
  }

  // ─── L3: Skill Registry (passthrough) ───────────────────────────────────────

  /** Register a draft auto-generated skill (disabled by default) */
  async registerDraftSkill(skill: CrystallizedSkill): Promise<void> {
    const def: SkillDefinition = {
      id: skill.id,
      name: skill.name,
      description: `Auto-generated skill: ${skill.trigger}`,
      icon: '✨',
      version: '1.0',
      author: 'system',
      category: 'custom',
      tags: ['auto-generated'],
      chatTriggerable: true,
      chatKeywords: [skill.trigger],
      order: 999,
      enabled: false, // always disabled until user confirms
      systemPrompt: `这是一组自动生成的步骤：\n${skill.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}`,
      examplePrompts: [skill.trigger],
      requiredContext: [],
      optionalContext: [],
      maxSteps: skill.steps.length,
      showSteps: false,
      autoGenerated: true,
    };
    await skillRegistry.saveCustomSkill(def);
  }

  /** Get all auto-generated skills */
  getAutoGeneratedSkills(): SkillDefinition[] {
    return skillRegistry.getAllSkills().filter((s) => s.autoGenerated);
  }
}

export const layeredMemoryStore = new LayeredMemoryStoreImpl();