/**
 * V131 L4→L3 PatternExtractor — crystallizes repeated patterns into skills
 * Triggers when the same patternSignature appears ≥ 3 times.
 */

import type { EpisodicEntry } from './EpisodicMemory';

export interface CrystallizedSkill {
  id: string;
  name: string;
  trigger: string;
  steps: string[];
  confidence: number; // based on repetition count (0–1)
  autoGenerated: true;
}

class PatternExtractorImpl {
  /**
   * Analyze episodic entries and return a crystallized skill if threshold met.
   * Returns null if fewer than 3 entries share the same patternSignature.
   */
  extract(entries: EpisodicEntry[]): CrystallizedSkill | null {
    if (entries.length < 3) return null;

    // Group by patternSignature
    const bySig = new Map<string, EpisodicEntry[]>();
    for (const e of entries) {
      const list = bySig.get(e.patternSignature) ?? [];
      list.push(e);
      bySig.set(e.patternSignature, list);
    }

    // Find signature with ≥ 3 entries
    let bestSig: string | null = null;
    let bestCount = 0;
    for (const [sig, list] of bySig) {
      if (list.length >= 3 && list.length > bestCount) {
        bestSig = sig;
        bestCount = list.length;
      }
    }

    if (!bestSig) return null;

    const group = bySig.get(bestSig)!;
    // Derive taskType from entries
    const taskType = group[0].taskType;
    const firstInput = group[0].inputs;

    // Build skill name from taskType
    const name = `Auto: ${taskType.replace(/_/g, ' ')}`;

    // Extract steps from inputs (flatten object keys to step descriptions)
    const steps = Object.entries(firstInput)
      .slice(0, 5)
      .map(([k, v]) => `${k}: ${String(v)}`);

    return {
      id: `auto-${crypto.randomUUID().slice(0, 8)}`,
      name,
      trigger: taskType,
      steps,
      confidence: Math.min(bestCount / 10, 1), // cap at 1, scale with count
      autoGenerated: true,
    };
  }
}

export const patternExtractor = new PatternExtractorImpl();