/**
 * Skill Generator Service - V99
 * 
 * Auto-generates Skill code framework from description.
 */

import type { SkillRecommendation } from '../../types/agentBuilder';
import { skillRegistry } from '../skills/skillRegistry';
import type { SkillDefinition } from '../skills/types';

const SKILL_CODE_TEMPLATE = `/**
 * Auto-generated Skill: {skillName}
 * Generated by V99 Natural Language Agent Builder
 * Created: {timestamp}
 */

import type {{ SkillDefinition, SkillExecutionContext }} from '../../services/skills/types';

export const {skillId}: SkillDefinition = {{
  id: '{skillId}',
  name: '{skillName}',
  description: '{description}',
  icon: '✨',
  category: 'custom',
  version: '1.0.0',
  enabled: true,
  chatTriggerable: true,
  chatKeywords: {chatKeywords},
  examplePrompts: [
    'Use {skillName}',
    'Try {skillName} skill',
  ],
  parameters: [],
  metadata: {{
    generatedBy: 'V99 Agent Builder',
    autoCreated: true,
  }},

  async execute(context: SkillExecutionContext): Promise<string> {{
    // TODO: Implement skill logic
    const {{ input, messages, personaId }} = context;
    
    // Add your implementation here
    const result = \`Skill {skillName} executed with input: \${input}\`;
    
    return result;
  }},
}};

// Register the skill
import {{ skillRegistry }} from '../../services/skills/skillRegistry';
skillRegistry.register({skillId});
`;

const SKILL_CATEGORY_KEYWORDS: Record<string, string[]> = {
  productivity: ['task', 'schedule', 'reminder', 'organize', 'plan', 'todo'],
  creative: ['write', 'story', 'art', 'design', 'creative', 'generate'],
  analysis: ['analyze', 'data', 'research', 'compare', 'insight'],
  lifestyle: ['life', 'health', 'fitness', 'food', 'travel'],
  developer: ['code', 'debug', 'test', 'deploy', 'git'],
  entertainment: ['game', 'movie', 'music', 'fun'],
};

/**
 * Generate a new Skill from description
 */
export async function generateSkill(description: string): Promise<SkillDefinition> {
  const skillId = `skill_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
  const skillName = generateSkillName(description);
  const category = detectCategory(description);
  const chatKeywords = extractKeywords(description);

  const skillCode = SKILL_CODE_TEMPLATE
    .replace(/{skillId}/g, skillId)
    .replace(/{skillName}/g, skillName)
    .replace(/{description}/g, description)
    .replace(/{chatKeywords}/g, JSON.stringify(chatKeywords))
    .replace(/{timestamp}/g, new Date().toISOString());

  // Write the skill file
  const filePath = `src/services/skills/generated/${skillId}.ts`;
  
  try {
    // For now, we'll create a minimal skill definition
    // In a full implementation, we would write the file
    const skill: SkillDefinition = {
      id: skillId,
      name: skillName,
      description,
      icon: '✨',
      category,
      version: '1.0.0',
      enabled: true,
      chatTriggerable: true,
      chatKeywords,
      examplePrompts: [
        `Use ${skillName}`,
        `Try ${skillName} skill`,
      ],
      parameters: [],
      metadata: {
        generatedBy: 'V99 Agent Builder',
        autoCreated: true,
      },
      async execute(context) {
        return `Skill ${skillName} executed with input: ${context.input}`;
      },
    };

    return skill;
  } catch (error) {
    console.error('Failed to generate skill:', error);
    throw error;
  }
}

/**
 * Generate skill name from description
 */
function generateSkillName(description: string): string {
  const words = description.split(/\s+/)
    .filter(w => w.length > 2)
    .slice(0, 2)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());
  
  return words.join('') || 'CustomSkill';
}

/**
 * Detect skill category from description
 */
function detectCategory(description: string): SkillDefinition['category'] {
  const lowerDesc = description.toLowerCase();
  
  for (const [category, keywords] of Object.entries(SKILL_CATEGORY_KEYWORDS)) {
    if (keywords.some(kw => lowerDesc.includes(kw))) {
      return category as SkillDefinition['category'];
    }
  }
  
  return 'custom';
}

/**
 * Extract keywords for chat triggering
 */
function extractKeywords(description: string): string[] {
  const words = description.split(/\s+/)
    .filter(w => w.length > 3)
    .slice(0, 5);
  
  return words;
}

/**
 * Recommend skills based on agent capabilities
 */
export async function recommendSkills(capabilities: string[]): Promise<SkillRecommendation[]> {
  const recommendations: SkillRecommendation[] = [];
  
  // Get existing skills from registry
  const existingSkills = skillRegistry.getAllSkills();
  
  // Score existing skills by relevance
  for (const skill of existingSkills) {
    const relevance = calculateRelevance(skill, capabilities);
    if (relevance > 0.2) {
      recommendations.push({
        id: skill.id,
        name: skill.name,
        description: skill.description,
        category: skill.category,
        relevance,
        selected: relevance > 0.5,
      });
    }
  }
  
  // Sort by relevance
  recommendations.sort((a, b) => b.relevance - a.relevance);
  
  return recommendations.slice(0, 10);
}

/**
 * Calculate relevance score between skill and capabilities
 */
function calculateRelevance(skill: SkillDefinition, capabilities: string[]): number {
  let score = 0;
  
  const skillText = `${skill.name} ${skill.description} ${skill.category}`.toLowerCase();
  
  for (const cap of capabilities) {
    const lowerCap = cap.toLowerCase();
    if (skillText.includes(lowerCap)) {
      score += 0.3;
    }
    // Check for partial matches
    const capWords = lowerCap.split(/\s+/);
    for (const word of capWords) {
      if (word.length > 3 && skillText.includes(word)) {
        score += 0.1;
      }
    }
  }
  
  return Math.min(1, score);
}

export default generateSkill;
