/**
 * V131 useLayeredMemory — React hook for accessing all 5 memory layers
 */

import { useCallback, useEffect, useState } from 'react';
import { layeredMemoryStore } from '../services/memory/LayeredMemoryStore';
import { useStore } from '../store';
import type { EpisodicEntry } from '../services/memory/EpisodicMemory';
import type { InsightEntry } from '../services/memory/InsightIndexer';
import type { GlobalFact } from '../services/memory/GlobalFactsStore';
import type { SkillDefinition } from '../services/skills/types';

export interface LayeredMemoryData {
  metaRules: readonly string[];
  recentSessions: EpisodicEntry[];
  insights: InsightEntry[];
  globalFacts: GlobalFact[];
  autoSkills: SkillDefinition[];
}

export function useLayeredMemory() {
  const [data, setData] = useState<LayeredMemoryData>({
    metaRules: [],
    recentSessions: [],
    insights: [],
    globalFacts: [],
    autoSkills: [],
  });

  const activeLayer = useStore((s) => s.activeLayer ?? 'All');

  const refresh = useCallback(async () => {
    const [recentSessions, insights, globalFacts, autoSkills] = await Promise.all([
      layeredMemoryStore.queryEpisodic('', 20),
      Promise.resolve(layeredMemoryStore.getAllInsights()),
      layeredMemoryStore.getAllGlobalFacts(),
      Promise.resolve(layeredMemoryStore.getAutoGeneratedSkills()),
    ]);

    setData({
      metaRules: layeredMemoryStore.getMetaRules(),
      recentSessions,
      insights,
      globalFacts,
      autoSkills,
    });
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return {
    ...data,
    activeLayer,
    refresh,
  };
}