/**
 * MUI Icons → Lucide React icon mapping
 * Replace @mui/icons-material imports with lucide-react equivalents
 */

import {
  Plus as AddIcon,
  ArrowLeft as ArrowBackIcon,
  Wand2 as AutoAwesomeIcon,
  BarChart3 as BarChartIcon,
  Zap as BoltIcon,
  Calendar as CalendarMonthIcon,
  MessageCircle as ChatIcon,
  CheckSquare as CheckBoxIcon,
  CheckCircle as CheckCircleIcon,
  X as CloseIcon,
  Trash2 as DeleteIcon,
  FileText as DescriptionIcon,
  Download as DownloadIcon,
  Edit3 as EditIcon,
  Mail as EmailIcon,
  ChevronUp as ExpandLessIcon,
  ChevronDown as ExpandMoreIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Puzzle as ExtensionIcon,
  Heart as FavoriteIcon,
  Heart as FavoriteBorderIcon, // FavoriteBorder uses same filled heart
  FileDown as FileDownloadIcon,
  Zap as FlashOnIcon,
  Users as GroupIcon,
  Cpu as HubIcon,
  Brain as MemoryIcon,
  Server as NetworkIcon,
  BrainCog as MultiAgentIcon,
  Palette as ScenesIcon,
  Menu as MenuIcon,
  Lightbulb as PsychologyIcon, // closest to PsychologyAlt
  RefreshCw as RefreshIcon,
  Settings as SettingsIcon,
  ShoppingCart as CartIcon,
  Bot as SmartToyIcon,
  TrendingDown as TrendingDownIcon,
  ArrowRight as TrendingFlatIcon,
  TrendingUp as TrendingUpIcon,
  Terminal as TerminalIcon,
  Activity as ActivityIcon,
  Plus, // AddIcon duplicate
  ArrowLeft, // ArrowBackIcon duplicate
  X, // CloseIcon duplicate
  Check,
  Star as StarIcon,
  FileText as DocIcon,
  Clock as TimeIcon,
  Tag as TagIcon,
  FileText as ArticleIcon,
  Globe as UrlIcon,
  StickyNote as NoteIcon,
  AlignLeft as TextIcon,
  MessageCircle as MessageIcon,
  Clock as ScheduleIcon,
  List as ListIcon,
} from 'lucide-react';

// Re-export with MUI-compatible names
export {
  AddIcon,
  ArrowBackIcon,
  AutoAwesomeIcon,
  BarChartIcon,
  BoltIcon,
  CalendarMonthIcon,
  ChatIcon,
  CheckBoxIcon,
  CheckCircleIcon,
  CloseIcon,
  DeleteIcon,
  DescriptionIcon,
  DocIcon,
  DownloadIcon,
  EditIcon,
  EmailIcon,
  ExpandLessIcon,
  ExpandMoreIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ExtensionIcon,
  FavoriteIcon,
  FavoriteBorderIcon,
  FileDownloadIcon,
  FlashOnIcon,
  GroupIcon,
  HubIcon,
  NetworkIcon,
  MemoryIcon,
  MultiAgentIcon,
  MenuIcon,
  PsychologyIcon,
  RefreshIcon,
  SettingsIcon,
  CartIcon,
  SmartToyIcon,
  TrendingDownIcon,
  TrendingFlatIcon,
  TrendingUpIcon,
  ActivityIcon,
  ScenesIcon,
  StarIcon,
  TimeIcon,
  TagIcon,
  ArticleIcon,
  UrlIcon,
  NoteIcon,
  TextIcon,
  MessageIcon,
  ScheduleIcon,
  ListIcon,
  TerminalIcon,
};
